### ISSUE TITLE
卡片笔记/微语 错误

### ISSUE THREAD

**Issue by 52linglong** [emlog/emlog#125]
未登录用户/游客 前端访问 /t/ SQL报错
[![](https://s4.ax1x.com/2021/12/08/oRxcAU.png)](https://s4.ax1x.com/2021/12/08/oRxcAU.png)

include\model\twitter_model.php：pro
[![](https://s4.ax1x.com/2021/12/08/oRvvwT.png)](https://s4.ax1x.com/2021/12/08/oRvvwT.png)

include\model\twitter_model.php：5.3.1
[![](https://s4.ax1x.com/2021/12/08/oRvxTU.png)](https://s4.ax1x.com/2021/12/08/oRvxTU.png)

未登录用户/游客不存在 `UID` ，希望修复此功能。

**Comment by emlog** [comment]
pro的卡片笔记并不支持前台游客访问，只有后台作者可见。
