### ISSUE TITLE
jQuery is duplicated

### ISSUE THREAD

**Issue by codersclub** [emlog/emlog#132]
At the moment **jQuery is placed twice** in the emlog:
1) admin/views/js/jquery.min.3.5.1.js
2) content/templates/default/js/jquery.min.3.5.1.js

It would be nice to store jQuery only once, i.e. in the common assets folder:
BLOG_URL/assets/jquery.min.3.5.1.js

**Comment by kohunglee** [comment]
maybe the folder **admin** is not suitable to import the external link.
they are two independent files.
emm....This solution is also appropriate.but kind of weird 

可能 **admin** 文件夹不适合去引入admin之外的链接吧。
他们是两个独立的文件。
嗯，不过这种解决方式可能也合适。就是有点奇怪。

**Comment by emlog** [comment]
我希望模板系统相对保持独立性，不去依赖后台的js和css库。
