### ISSUE TITLE
Ignore .gitignore

### ISSUE THREAD

**Issue by codersclub** [emlog/emlog#134]
I want to add my own ignored files into the .gitignore files, but I can not do that because of this file is included into the git index :(

It would be nice to remove .gitignore from the repository. but add a .gitignore.sample file.
This solution would allow each developer to add their own files to the ignore list.

**Comment by emlog** [comment]
我想你可以先直接添加你需要的内容到.gitignore，并提交上来， 如果这些目录文件不涉及隐私的话。
