### ISSUE TITLE
Oh mine God! The repository is corrupted!

### ISSUE THREAD

**Issue by codersclub** [emlog/emlog#141]
I see the repository emlog/emlog become corrupted.

All commits older than 2017-07-18 17:13:12 +0800 (a391dce226ba5f6cd70fdbbe05680ecf1cf2a63a [a391dce]) were duplicated.

Before the end of 2021 year there were about 1000 commits, 
but after the new year in there were already **2122** commits.

**Comment by codersclub** [comment]
Wow! Not duplicated, but repeated THREE TIMES!

**Comment by codersclub** [comment]
By the way, my fork https://github.com/codersclub/emlog contains an uncorrupted copy of your repository!
You can use it to restore your repository...

**Comment by emlog** [comment]
thx i fix that sorry ……I tried to fix some commit logs but encountered errors

**Comment by codersclub** [comment]
Unfortunately the problem is NOT solved.
Some starting commits are ok (from the beginning up to a391dce226ba5f6cd70fdbbe05680ecf1cf2a63a (2017-07-18 17:13:12 +0800)
But all the later commits are duplicated :(

**Comment by codersclub** [comment]
1) This set of commits **is correct** and must be protected from deletion:
starting with 9d473cfc811fcdb508e1bfd3a11d9f85ed3f3daa and ending with ffc1d2a5c26b3ba46d6011e808649ee47c2ec241 (tag pro-1.1.1).

2) Invalid set of duplicate commits starting from 5031324d5639e8a8409b6a4bd63f07692ac0f314 and ending with cc8a1854c23d1170cab5d0ee069d7ba3b43cb872 **must be removed**!

3) 2 new commits starting from January 5 should be reattached to the real parent commit ffc1d2a5c26b3ba46d6011e808649ee47c2ec241 (tag pro-1.1.1).

**Comment by vibbow** [comment]
The commit are not duplicated.
Just remove the existing tags and retag from master should be fine

**Comment by vibbow** [comment]
https://github.com/vibbow/emlog
You can use this as reference, to see how the fix works.

**Comment by vibbow** [comment]
Just delete all tags from here (except 5.3.1)
https://github.com/emlog/emlog/tags

Run following commands in local, then do a `git push --tags`

`git tag -a -m "" -f 6.0.0 cfe0eb4d3c45670138569c5e137706518d71740b
git tag -a -m "" -f pro-1.0.2 ae48fbb3e2235527a35f1a2dd733356e36357259
git tag -a -m "" -f pro-1.0.3 a39e20fd08e958bba9f7f1ac84953e07f1355983
git tag -a -m "" -f pro-1.0.4 ba296dcf175ce537ba15fdbf441d52f0082760f2
git tag -a -m "" -f pro-1.0.5 94f29d21b8de580a3e552d55253d79edb1c0cf93
git tag -a -m "" -f pro-1.0.6 37321ffaf892cb33dc33503ba6df1ff796b8b105
git tag -a -m "" -f pro-1.0.7 0e2022d8217696cab76c9b41b5b322718f72c3df
git tag -a -m "" -f pro-1.1.1 10d3aeb1515b6b953a71b0481833012c8b5aee50`

**Comment by codersclub** [comment]
I am sorry, but that fix is a bad solution :(
All the people who cloned your repository in 2021 year and then pulled it 2022 will have a corrupted (duplicated) set of commits, because of you have changed many of commit hash IDs :(

I think the best solution to solve this incident is to clone from any OLD fork and then reaupload your repository totally.
For example, my clone https://github.com/codersclub/emlog still contains a full and correct commit set of your repository.

**Comment by vibbow** [comment]
This didn't change any commit id

**Comment by emlog** [comment]
Thank you, everybody. It looks good now ：）

**Comment by codersclub** [comment]
> This didn't change any commit id

It is not true!
At 26 December of 2021 the commit tagged as "pro-1.1.1" have had hash ID = c757269ace6150459e510d3214e60fcef2cb677c.
But today it have a hash ID = 10d3aeb1515b6b953a71b0481833012c8b5aee50
Do you see the difference? 
And the same problem with yet another 611 commits!
This is why my git after pulling creates 611 new commits, duplicating the old 611 commits.

**Comment by vibbow** [comment]
just the tag linked to another commit.
It didn't change commit itself.

**Comment by emlog** [comment]
i use git filter-branch to change the commit log ’s email . it was empty before .mybe that change the commit log id...

**Comment by codersclub** [comment]
Just look at ANY OLD commit!
For example: https://github.com/emlog/emlog/commit/ffc1d2a5c26b3ba46d6011e808649ee47c2ec241
You will see an error message:
**This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.**
And the same problem with 611 other lost commits.
They are present in the repository, but not linked to any branch. They hang in the void like lost...

**Comment by vibbow** [comment]
Since there were two branches, regardless we need to choose one branch as our main branch and discard another one.

The commit id you mentioned was existed is only because there is a tag referer it. and now the referer is gone, so it didn't belong to any branch.

**Comment by vibbow** [comment]
if you delete **ALL** tags in your local and do a `git fetch --tags origin`, you should get new tag information.

To fix the branch split issue, we had to either delete the tag or revert the entire repo to old version.

Obvious delete tag is the easy one.

**Comment by codersclub** [comment]
> The commit id you mentioned was existed is only because there is a tag referer it. and now the referer is gone, so it didn't belong to any branch.

You are wrong. 
According to the Git documentation, the sequence of commits and their affiliation to a branch is influenced solely by the hash of the commit itself, as well as the hashes of its parents and descendants.
Adding, removing and moving tags does not play any role in the formation of the commit index (sequence of commits).

**Comment by codersclub** [comment]
> To fix the branch split issue, we had to either delete the tag or revert the entire repo to old version.
No!
Tags will not help.
But reverting will only add unnecessary annoying garbage to the repository.
Only cloning/reuploading from old forked repository will restore the state to the right situation.

**Comment by vibbow** [comment]
> Adding, removing and moving tags does not play any role in the formation of the commit index (sequence of commits).

Not in this case.

In this case, the splited 'branch' is not referencing by any branch, instead it was referencing by a tag. (I don't know how did it happened, but it happened).

Delete the tag caused this 'branch' become a orphan 'branch'.

**Comment by vibbow** [comment]
@codersclub You can try delete all tags in your local repo, you can see the splited 'branch' is magically disappeared.

Sure you can find the old commits by looking the commit it, but `git gc` should trim them.

**Comment by codersclub** [comment]
You think only of yourself and do not care at all about those who have their own additional branches and tags in their cloned repositories. All of them will also be unlinked from the renewed main "master" branch and will hang in the splitted unknown branch.
I don’t agree to lose all my previously prepared pull requests due to someone's inadvertent mistake!

**Comment by vibbow** [comment]
Again, the splited 'branch' is not a branch.

**Comment by codersclub** [comment]
> Again, the splited 'branch' is not a branch.

No matter. My branches are linked to that lost commits.

> The master branch is never been affected.

The master branch was corrupted already at 5 January.

> If you did a fresh clone, and compare to exist one, you can see the master branch is untouched.

The fresh clone contains the master branch that is already absolutely new and does not correspont to ols master branch.

You can try to pull from old clone and you will see that alot of commits will be duplicated :(

**Comment by codersclub** [comment]
> the commit id in master branch is never changed, is absolutely the old one.

Again:
Just check the commit ids with the old clone, that contains the previous correct hash IDs:
https://github.com/codersclub/emlog

> the commit id in master branch is never changed, is absolutely the old one.

No, you deleted a significant part of the old master branch with the correct hash id, and created a new set of deleted commits, but with new hash id!

**Comment by vibbow** [comment]
because those were never master branch commits

**Comment by vibbow** [comment]
@codersclub https://github.com/vibbow/test/
Try clone this repo, and check which branch is this commit belong to: 937fbfd

**Comment by codersclub** [comment]
Such methods of hardly rewriting the commit history can only be used when only one person is involved in the development.
But if you work in a team, any distortion of the commit history is absolutely  unacceptable!
This is what the best git practices recommend.

**Comment by vibbow** [comment]
There is no way to attach to a "tag" only "branch".
So you can't merge or rebase it.

The only reason this branch exists, is a tag is referencing it.

The only way to fix the split branch, is re-assign the tag to correct commit.

**Comment by codersclub** [comment]
While I'm cloning your test repository, try to clone https://github.com/codersclub/emlog 
and make sure it doesn't have any lost commits. All commits with old IDs are in the master branch, not hanging in the air :)

**Comment by vibbow** [comment]
I see why you have so many confliet commits.

the emlog/emlog have two branchs
the 'master branch' (commits have email, create by git push) and 'branch for tags' (commits don't have email, created by github).

Your work are based on the 'branch for tags', not the master branch.

therefore then the tag is deleted, the 'branch for tags' are gone, so you lost the track to that branch.

**Comment by vibbow** [comment]
@codersclub there is a way to fix it, hold on a second, let me try that first.

**Comment by codersclub** [comment]
Playing with the https://github.com/vibbow/test/ .
1) Original state:

![vibbow-test1](https://user-images.githubusercontent.com/3078296/148229252-8557461e-847f-4c1f-81cf-c95ca91f1454.png)

2) Removing the tag "tag1"
![vibbow-test2](https://user-images.githubusercontent.com/3078296/148229384-044b7b67-47c2-4741-976a-29bb602c20e8.png)

3) Merging the commit 937fbfdec97 to the master branch:

![vibbow-test3](https://user-images.githubusercontent.com/3078296/148229685-521819bc-fd13-44c6-8049-42c5a31e0a48.png)

And I see NO problems with tags/merging/rebasing :)

And about your solution with rebasing:
It is not a good solution because of the rebase operation is beeng changing all the rebased commits.
So we will have yet another NEW commit history :(

**Comment by vibbow** [comment]
There were two branchs of emlog/emlog
One is master branch, another is tag branch.

Github magically cherry pick all commits from master branch to the tag only branch, to made the tag (by web ui).

So those two branchs looks like duplicated branch.

To fix this issue and clean the duplicates, we choiced to keep the master branch and eliminate all tags ( so the tag branch will become orphan branch and disappeared from history )


Unfortunately your fork is forking from the tag branch, not the master branch. Since when the tag branch is gone, your repo lost the track to the upstream.

**Comment by vibbow** [comment]
> Playing with the https://github.com/vibbow/test/ .
> 
>     1. Original state:
> 
> 
> ![vibbow-test1](https://user-images.githubusercontent.com/3078296/148229252-8557461e-847f-4c1f-81cf-c95ca91f1454.png)
> 
>     2. Removing the tag "tag1"
>        ![vibbow-test2](https://user-images.githubusercontent.com/3078296/148229384-044b7b67-47c2-4741-976a-29bb602c20e8.png)
> 
>     3. Merging the commit 937fbfdec97 to the master branch:
> 
> 
> ![vibbow-test3](https://user-images.githubusercontent.com/3078296/148229685-521819bc-fd13-44c6-8049-42c5a31e0a48.png)
> 
> And I see NO problems with tags/merging/rebasing :)
> 
> And about your solution with rebasing: It is not a good solution because of the rebase operation is beeng changing all the rebased commits. So we will have yet another NEW commit history :(

Because I was doing cherry-pick, the two commits are from same commiter.

But emlog/emlog's tag branch is not, github messed up with something (like email) so git can't tread those as same commits.

**Comment by vibbow** [comment]
If merging is works on your side, you can merge upstream/master info your origin/master, it should be the same.

**Comment by codersclub** [comment]
> Unfortunately your fork is forking from the tag branch, not the master branch.
My fork is just a stupid clone of the old not corrupted emlog/emlog repository.
It is bit-by-bit is equal to the original repo as it was before 2022 year!
But in 2022 the original repository was broken :(

I don't know how else to explain the severity of the problem with modifying the commit history ...
I urge you to follow best practices for collective development and restore the repository to its old state before it crashed, but you suggest new options to make the situation even worse :(

**Comment by vibbow** [comment]
Github messed up something, your fork is a broken fork. You can see all your commiter (come from fork) have no email address.

**Comment by vibbow** [comment]
@codersclub Your repo also have planty commits from emlog/emlog:master branch, but not in your branch.
https://github.com/codersclub/emlog/commit/a77d261c3589189f621f586132688cba0dbc375a

**Comment by codersclub** [comment]
> Your own commits are also duplicated

It should be so. 
Because there was my commit proposed as a pull request, which was replaced with a copy after the pull request was approved. 

> It's not modify commit history, it's abandon a broken branch, the master branch is never touched.

If you consider yourself right that the main branch of this repository has not changed in any way, then please explain to me why and from where 611 lost commits suddenly appeared in this repository, are an exact copy of the commits that I have NOT lost and are present in the main branch " master"? 
That being said, the lost commits appeared in 2022 but I haven't touched my repository since 2021?

Maybe someone have stolen some commits from my repository to themselves and then deleted them? :)

**Comment by vibbow** [comment]
Because github fucked things up.

Github duplicated all commits to a tag branch, and it's not used by emlog/emlog, no one is pushed to that tag branch.
But after fork, github thought that branch is master.

Secondly, no one did force push, just delete tags, why should that case commit lost? because thost commit should never exist in the first place.

**Comment by codersclub** [comment]
> your fork is a broken fork. You can see all your commiter (come from fork) have no email address.

It is not my fork is broken.
It was no email address in original emlog/emlog commits that was just copied to my fork:
https://github.com/emlog/emlog/commit/6f8028027e09e643125e96ec16916e037dd52d79.patch

**Comment by vibbow** [comment]
As you raised this issue in the first place, there are duplicate commits in this repo for long time.

for the one you mentioned, the two duplicated commits are:
https://github.com/emlog/emlog/commit/6117b397b496832ffdd3e48db7307040d780714a
https://github.com/emlog/emlog/commit/6117b397b496832ffdd3e48db7307040d780714a.patch

https://github.com/emlog/emlog/commit/6f8028027e09e643125e96ec16916e037dd52d79
https://github.com/emlog/emlog/commit/6f8028027e09e643125e96ec16916e037dd52d79.patch

one is in the master branch (the developer working with), with email address.
one is in the branch old `pro-1.1.1` tag referencing to, with only a name, no email address.

The `pro-1.1.1` tag branch have no future commits, the master branch have few commits ahead.

No one is use the tag branch, no one commit into it, that branch even don't have a branch name, only Github copying everything into it. 

Somehow, when you fork the repo, github thought that tag branch is master branch, and ignored the real master branch.


No one is alter the git history, just delete the tags which referring the wrong branch, and the tag branch with nothing referencing are gone.

This is what happened to this repo.

======

Now, to solve your problem, we have two solutions.

1. emlog/emlog repo re-introduce all those duplicated commits, and not sure if github will continue fuck with this branch in the future. or we merge the behind tag branch into ahead master branch.

2. you merge the upstream/master into your master, to align the emlog/emlog master.

**Comment by codersclub** [comment]
Here's what I found out:
Did the commits on my fork match the emlog/emlog commits before? as I cloned from there.
However, on January 5, the emlog/emlog repository was rewritten to clarify the email committer. This caused the github to recalculate the hashes for the changed commits!
At the same time, the vibbow/emlog repository was not overwritten, and exactly the commit hashes that are present in my fork are preserved in it!
From this it becomes clear why vibbow insists that the master branch has not changed. 
**So, wibbow is right!** 
Indeed, nothing has changed in the vibbow/emlog!
However, the emlog/emlog has definitely replaced a significant amount of commits! 
Those, **I'm right too!** :)
Just compare the same commits in vibbow/emlog and emlog/emlog!

**Comment by vibbow** [comment]
vibbow/emlog is a new fork by today, to test different possibility of merging/align code.

**Comment by codersclub** [comment]
However, the vibbow/emlog repository contains the correct commit hashes that are present in my fork!
I am trying to add vibbow/emlog as a new remote ...

**Comment by vibbow** [comment]
No don't. mine is gonna delete in any future with no gurrante.

**Comment by codersclub** [comment]
Alas, my assumptions turned out to be wrong :(
The vibbow/emlog repository contains TWO parallel sets of commits: one set fully matches the modified emlog / emlog set, and the second set fully matches my fork.
In other words, vibbow/emlog repository contains duplicated commits, for example:
10d3aeb1515b6b953a71b0481833012c8b5aee50 from emlog/emlog?
ffc1d2a5c26b3ba46d6011e808649ee47c2ec241 from vibbow/emlog (equal to the same in my fork)

**Comment by vibbow** [comment]
I found different git GUI tool have different behaviour.

To exam vibbow/emlog

for gitk, it didn't show the 'tag branch'.
for example, it didn't show ffc1d2a in visual branch history
![图片](https://user-images.githubusercontent.com/6408107/148265662-2a124b1b-c275-42a4-b459-465b41380690.png)


for github web, it show the tag branch in master.
for example, it show ffc1d2a is following by 10d3aeb in master branch
![图片](https://user-images.githubusercontent.com/6408107/148265679-720c0039-2a60-4c4b-96d6-08ca18946c47.png)


for sourcetree, it show the tag branch in a standalone branch
![图片](https://user-images.githubusercontent.com/6408107/148265708-64a4399f-7354-4c0f-99a6-bc20f2b64d49.png)

**Comment by vibbow** [comment]
I'm using sourcetree as daily git tool.
So I treat the two duplicate commit stream as two different branch.

![图片](https://user-images.githubusercontent.com/6408107/148265895-fb046bc2-8896-4a61-9aa6-08ab1fbd8b0d.png)

**Comment by codersclub** [comment]
> for gitk, it didn't show the 'tag branch'.

It SHOWS a parallel set of commits (duplicated) right in master branch.
Just click to the red down arrow!

Additionally:
TortoiseGit, SmartGit and TortoiseHG shows the duplicated commit set in the master branch too.

**Comment by vibbow** [comment]
The split is happened since a391dce ,this commit have a tag with it.

Afterward, it split into to stream
9d473cf and 5031324
both treat a391dce as their parent commit.

Since then, every commit are duplicated into to commit stream.
but the duplication is not happened in real time, instead it happened when another tag is created.

**Comment by codersclub** [comment]
I tried to clone codersclub/emlog and then add the last 2 commits from vibbow/emlog of 5 January.
The result was the best!

**Comment by codersclub** [comment]
Showing the result that have all the commit hashes unmodified plus added 3 commits of 5 January.
No duplicates, no lost commits.
https://github.com/codersclub/emlog-pro.git
How do you like that, Elon Musk? ;)
