### ISSUE TITLE
cover 

### ISSUE THREAD

**Issue by 52linglong** [emlog/emlog#142]
上传文章封面，选择图片，裁剪并上传时取消，无法再次裁剪并上传。

![动画](https://user-images.githubusercontent.com/51982959/148684430-46f40469-9759-43c0-9957-1a58e30c844e.gif)

**Comment by 52linglong** [comment]
[![http://inews.gtimg.com/newsapp_ls/0/14403252367/0](http://inews.gtimg.com/newsapp_ls/0/14403252367/0)](http://inews.gtimg.com/newsapp_ls/0/14403252367/0)

**Comment by emlog** [comment]
哪个版本？试着升级到1.1.1试试。

**Comment by 52linglong** [comment]
升级1.1.1，清除缓存，已正常使用，谢谢
