### ISSUE TITLE
侧边栏标签缓存是否存在错误

### ISSUE THREAD

**Issue by 52linglong** [emlog/emlog#154]
![New_Issue_·_emlogem-2022-01-30_11-36-15](https://user-images.githubusercontent.com/51982959/151685863-51b04a9f-fa17-454f-9dcf-1e758533b609.png)

> $usenum = substr_count($show_tag['gid'], ',') - 1;

若 $show_tag['gid'] = '1,2,3,4'，则 $usenum = 2

若 $show_tag['gid'] = ''，则 $usenum = -1

这样侧边栏标签缓存就存在了错误

修改成 *$usenum = empty($show_tag['gid']) ? 0 : substr_count($show_tag['gid'], ',') + 1;* 可否？

**Comment by emlog** [comment]
是的这里确实是有问题，按照你的写法修改了。
