### ISSUE TITLE
A stored XSS vulnerability exists in emlog pro-1.2.1

### ISSUE THREAD

**Issue by my123px** [emlog/emlog#161]
Vulnerability location: system - settings - seo optimization
Vulnerability Url: http://ip:port/emlog/admin/setting.php?action=seo_save
Vulnerability parameters: site_title, site_description
![image](https://user-images.githubusercontent.com/33975676/156132118-6914d457-ded3-490e-9a54-7c7b286b535b.png)
Modify the site_title value to 11111%22%3E%3Csvg+onload%3Dalert%281%29%3E and the site_description value to 2222%3C%2Ftextarea%3E%3Csvg+onload%3Dalert%282%29%3E
![image](https://user-images.githubusercontent.com/33975676/156132216-b01e7e5c-77a5-474d-8fe5-c2285c0e07c4.png)
The results are as follows
![image](https://user-images.githubusercontent.com/33975676/156132362-e38a3082-a840-4ff3-be68-2618038c96d0.png)
![image](https://user-images.githubusercontent.com/33975676/156132378-f296ddaf-53f3-4f09-8544-390c6a65aafa.png)
![image](https://user-images.githubusercontent.com/33975676/156132404-874abc1b-49e6-40af-ab92-91d3b8aa71eb.png)
![image](https://user-images.githubusercontent.com/33975676/156132431-8ac9e5a0-8119-437c-a522-a3d32543437c.png)

**Comment by emlog** [comment]
感谢反馈，不过请不要在公开issue里提交安全风险，该issue会在一周后删除。
