### ISSUE TITLE
There is a CSRF vulnerability in adding a friend chain function point in emlog pro-1.2.1

### ISSUE THREAD

**Issue by my123px** [emlog/emlog#162]
Vulnerability Location: Appearance - Link - Add Link
![image](https://user-images.githubusercontent.com/33975676/156134132-469b958c-5d1d-4ba3-90e1-23c50cdde76d.png)
The request to add a friend chain is as follows, there is no token in the request packet, and the request header Referer can still be successfully requested
![image](https://user-images.githubusercontent.com/33975676/156134202-252c7ee8-282b-415f-8274-594e6ca749ba.png)

**Comment by emlog** [comment]
感谢反馈，不过请不要在公开issue里提交安全风险，该issue会在一周后删除。
