### ISSUE TITLE
There is a csrf vulnerability in the review comment function point in emlog pro-1.2.1

### ISSUE THREAD

**Issue by my123px** [emlog/emlog#163]
Vulnerability Location: Comments - Review
Vulnerability url: http://ip:port/emlog/admin/comment.php?action=batch_operation
![image](https://user-images.githubusercontent.com/33975676/156134706-e3c6dae2-fe3c-4840-b42d-735efc05138a.png)
The audit request is as follows, there is no token in the request packet, and the request header Referer can still be successfully requested
![image](https://user-images.githubusercontent.com/33975676/156134771-86f2e916-6f82-42fc-80fe-cc67a8ba5764.png)

**Comment by emlog** [comment]
感谢反馈，不过请不要在公开issue里提交安全风险，该issue会在一周后删除。
