### ISSUE TITLE
XSS vulnerability 

### ISSUE THREAD

**Issue by e11usion** [emlog/emlog#164]
A XSS vulnerability was discovered in emlog pro v1.2.1.
After other users browse the page, XSS code will be triggered,attacker can execute code or steal cookies.

1.Use the test account to publish an article with malicious code `<script>alert(1)</script>`.
![image](https://user-images.githubusercontent.com/75007743/157810911-5dcb0624-93ed-41fd-9559-da770529abf9.png)
2.Use another account to view this article and successfully trigger XSS.
![image](https://user-images.githubusercontent.com/75007743/157810923-06886cd5-bd03-44e9-9b8e-ba2f56758848.png)
![image](https://user-images.githubusercontent.com/75007743/157810930-9c6af2fe-f770-419b-ad2e-512b42abcd27.png)

Location of vulnerability
http://x.x.x.x/admin/article_save.php?action=add
![image](https://user-images.githubusercontent.com/75007743/157810996-ecbf50ac-148d-465b-a751-60bb475c9f8d.png)

https://user-images.githubusercontent.com/75007743/157811172-d7c25723-db45-4fcb-bec9-490f43901fbf.mp4

**Comment by emlog** [comment]
this is. feature, not bug.
