### ISSUE TITLE
Over Permission vulnerability

### ISSUE THREAD

**Issue by e11usion** [emlog/emlog#165]
Over Permission vulnerability was discovered in emlog pro v1.2.1.
User can delete pictures and videos uploaded by other users.

1.Log in with the test account test1 and upload a picture(图片4.png) in the multimedia resource management office.
![image](https://user-images.githubusercontent.com/75007743/157813001-32831532-ff95-4458-840e-c980029bc8a2.png)
2.Change the test account test2 and upload another picture(图片2.png) in the multimedia resource management office.
![image](https://user-images.githubusercontent.com/75007743/157813068-122549f6-d289-4023-8ebe-a219e138d993.png)
3.Click to delete the picture and tamper with the request.
![image](https://user-images.githubusercontent.com/75007743/157813205-54422939-e5f0-4033-b074-84b5c2a1fb59.png)
Change the parameter aid to 1 (it is the order in which pictures are uploaded. Because 图片4.png is uploaded for the first time, it is 1. Similarly, 图片2.png  is the second uploaded picture, so aid = 2 at this time)
![image](https://user-images.githubusercontent.com/75007743/157813313-729677e3-ab7d-4fe8-82a2-47bd51b709fd.png)
It shows that the deletion was successful, but the 图片2.png still exists.
4.Switch back to test1 account and find 图片4.png  has been deleted
![image](https://user-images.githubusercontent.com/75007743/157813449-7205abcd-3ac1-419f-b510-294405d32ff8.png)

ur:http://x.x.x.x/admin/media.php?action=delete&aid=1&token=50e7c347fd6faadd0a777e22f03125ab911e45ab

https://user-images.githubusercontent.com/75007743/157814033-9d70dbe1-b162-4478-ba93-bb695432c309.mp4

**Comment by emlog** [comment]
感谢上报，安全漏洞请通过 https://www.cnvd.org.cn/flaw/create 提交。这里将会近期删除。
