### ISSUE TITLE
setcookie function PHP 7.3.0+ support

### ISSUE THREAD

**Issue by zishang520** [emlog/emlog#167]
Alternative signature available as of PHP 7.3.0 (not supported with named parameters): [Migrating from PHP 7.2.x to PHP 7.3.x](https://www.php.net/manual/en/migration73.other-changes.php#migration73.other-changes.core.setcookie) 

>Support code snippets:
```php
if (PHP_VERSION_ID < 70300) {
    // setcookie(string $name, string $value = "", int $expires_or_options = 0, string $path = "", string $domain = "", bool $secure = false, bool $httponly = false): bool
} else {
    // setcookie(string $name, string $value = "", array $options = []): bool
}

**Comment by emlog** [comment]
Thank you. I will test and verify it recently.
