### ISSUE TITLE
侧边栏标签显示不全

### ISSUE THREAD

**Issue by Mr-xn** [emlog/emlog#180]
如题，当标签超过代码里限定的100个后就不展示了，这个不太合理吧 可以把展示的数量交给用户，比如在边栏-标签设置名称哪里可以同时设置数量，就像评论和文章设置数量一样。
PS，如果设置了数量可能需要适当修改 `$maxuse = 20;` 的值 或者改变下比例 https://github.com/emlog/emlog/blob/ee8f3c5b93ee9000294ec92b7ae90bdee5bdd5b1/include/lib/cache.php#L265

**Comment by emlog** [comment]
这里如果展示的太多 有些用户标签好几万。这里性能问题很严重。
