### ISSUE TITLE
删除文章不会自动更新侧栏的标签

### ISSUE THREAD

**Issue by tlogin2021** [emlog/emlog#181]
复现过程：添加一篇“测试”文章，加上“test”标签，删除“测试”后，侧栏标签依然显示“test”标签有“1 篇文章”，点进去却显示“抱歉，暂时还没有内容。”。

目前的解决办法是手动删除标签再添加回去。

环境是pro-1.4.0、apache、默认模板。

**Comment by emlog** [comment]
感谢反馈。
