### ISSUE TITLE
请问作者是否有重构打算？

### ISSUE THREAD

**Issue by zyimm** [emlog/emlog#182]
目前代码代码比较复古，代码风格和规范脱离现代PHP开发，建议作者考虑：
1. 组件按照psr 标准重构
2. 适用部分框架mvc 使用外部依赖实现
3. 支持composer
4. 改善一些代码设计风格，比如if藏绕，改用map实现？

其实很冒昧，因为目前有入门学者，通过您的项目刚入行接触

**Comment by emlog** [comment]
你好，我从来不觉得写代码还分现代和古代，任何框架和工具都有它的使用场景，有他的优点也有缺点，并不是没有成本的。就像我们切菜用菜刀就够了，没必要掏出2米长的青龙偃月刀。您提的建议都挺好，但是我还是喜欢具体的意见，比如多少行代码应该怎么写才更好。
