### ISSUE TITLE
XSS vulnerabilities in pro2.0.3

### ISSUE THREAD

**Issue by ez4s1mple1943** [emlog/emlog#229]
**Version(latest version)**
emlog_pro_2.0.3

**Actual behavior**
XSS vulnerabilities

**Steps to reproduce the behavior**

1.There is a stored xss in the article writing. The article body(文章正文) and article summary(文章摘要) has the vulnerability.

在写文章功能点，文章正文以及文章摘要处存在存储型xss
![image](https://user-images.githubusercontent.com/98327377/229009201-1e3461a9-9e6e-4f65-9d4f-9c82d6946b16.png)

![image](https://user-images.githubusercontent.com/98327377/229005128-b8aa3026-9d67-4d07-b95b-436a1eb4c0c9.png)

Go to the home page, the xss payload in article summary will be triggered first.
访问emlog首页，会先触发文章摘要中的xss
![image](https://user-images.githubusercontent.com/98327377/229005281-5a4720e2-17ee-4f73-b085-ff9a43206ed3.png)

And after click the article, the xss in article body will be triggered.
之后点击该文章，会触发文章正文的xss
![image](https://user-images.githubusercontent.com/98327377/229005367-48ce45ed-7726-4475-bed1-061c4a4c402b.png)

2. The vulnerability is in resources --> add resource classification, the classification name has the xss.
在资源-->添加资源分类中，分类名称存在xss漏洞
![image](https://user-images.githubusercontent.com/98327377/229005507-09197056-8f58-4961-aecb-1240c2908118.png)

![image](https://user-images.githubusercontent.com/98327377/229005744-f39d2cf4-08f8-4517-95d2-6ee05d4ac514.png)

After add a new resource classification, upload a file at will, then the vulnerability will be triggered, and it works when reloading the `/admin/media.php` page
在新创建的资源分类下，上传任意图片，即可触发xss，并且重新加载`/admin/media.php`页面时也会触发xss
![image](https://user-images.githubusercontent.com/98327377/229005883-ac70b809-1fca-4590-be11-4aa40f8cc5ab.png)

![image](https://user-images.githubusercontent.com/98327377/229006357-306b9dfc-97a5-40cb-9e11-dfad8b6d6b50.png)

3.And there is also a xss in home page bottom information.

在首页底部信息处存在存储性xss

![image](https://user-images.githubusercontent.com/98327377/229007219-37e34ac1-fd8a-4d31-95f3-65c46cf39619.png)

Save the settings, and go to home page.
保存设置后，访问主页，触发xss

![image](https://user-images.githubusercontent.com/98327377/229007128-883c0aed-22d4-41ba-a653-c4735c5c1013.png)

**Comment by emlog** [comment]
好的感谢反馈，资源分类这里确实应该处理下，其他部分支持html和js是特性，暂不处理。

**Comment by fliggyaa** [comment]
> 好的感谢反馈，资源分类这里确实应该处理下，其他部分支持html和js是特性，暂不处理。

这里第一处修复好像只是阻止了弹窗，但是实际还是执行了js，能够获取到cookie
