### ISSUE TITLE
Code Indentation Mess

### ISSUE THREAD

**Issue by codersclub** [emlog/emlog#232]
When viewed in any text editor, the Emlog code looks sloppy in some files because spaces and tabs are randomly used for indentation.
The real example from admin/views/comment.php:
```
                                </a>
								<?php if (User::haveEditPermission()): ?>
                                    <a href="javascript: em_confirm('<?= $ip ?>', 'commentbyip', '<?= LoginAuth::genToken() ?>');"
                                       class="badge badge-pill badge-warning">按IP删除</a>
								<?php endif ?>
                            </td>
                        </tr>
					<?php endforeach ?>
                    </tbody>
```
It is recommended to use PSR-1 + PSR-12 for the code style used in Emlog.

**Comment by emlog** [comment]
This problem was solved in the latest commit
style:PSR-12 use an indent of 4 spaces
