### ISSUE TITLE
EyouCms v1.6.2 存在反射型XSS漏洞

### ISSUE THREAD

**Issue by Hebing123** [emlog/emlog#238]
EyouCms v1.6.2 存在反射型XSS漏洞，系twitter.php文件中active_t参数过滤不严。

![image](https://github.com/emlog/emlog/assets/66168888/8e41f4b6-11a5-4f38-8646-8b56be13c0cd)

攻击者构造恶意链接：
/admin/twitter.php?active_t=%22%3E%3Cscript%3Ealert(1)%3C/script%3E

登陆后的用户触发xss。

![image](https://github.com/emlog/emlog/assets/66168888/e1cd5c6a-43c0-4e78-afa0-7225ed003131)

**Comment by emlog** [comment]
感谢反馈，下个版本修复下。

**Comment by Hebing123** [comment]
> 感谢反馈，下个版本修复下。

如果可以的话请建立一个security.md 谢谢，报告来自冰河安全团队。

**Comment by emlog** [comment]
不了谢谢。

**Comment by Hebing123** [comment]
好的，我们会通报本次漏洞给其他使用者 提醒他们进行修复。
