### ISSUE TITLE
Option::get('posts_name')

### ISSUE THREAD

**Issue by codersclub** [emlog/emlog#247]
The new feature: **Option::get('posts_name')** is not compatible with Multilingual idea.
Moreover, it can NOT be used even in a single-language English version!

It would be better to use language variables **lang('article')**, **lang('articles')**, etc.
If a site admin want to rename a post name, it can modify language files as he want easily.

For example:
lang('articles') => 'Articles',
lang('articles') => 'Posts',
lang('articles') => 'Postings',
lang('articles') => 'Publications',
lang('articles') => 'Contributions',
lang('articles') => '帖子',
lang('articles') => '投稿',
lang('articles') => '资源等',
etc.

**Comment by emlog** [comment]
I don't think this is a multi-language issue, this is a feature. In addition, I hope to set it up conveniently in the control panel instead of modifying the configuration file.
