### ISSUE TITLE
File Upload Vulnerability in pro2.1.14

### ISSUE THREAD

**Issue by feefersg** [emlog/emlog#249]
Version(latest version)
emlog_pro_2.1.14

Actual behavior
File Upload Vulnerability

Steps to reproduce the behavior

Emlog_pro has the capability to control uploaded file extensions, but it's already specified in the code that it's impossible to have the file extension of uploaded files as 'php.' (As shown below, attempting to save a file with the 'php' extension will automatically convert it to 'x'). There's no way to bypass this restriction. 

Emlog_pro 具有控制上传文件后缀名的功能，但是在代码中已经写明是无法使得上传文件名的后缀为php的，（如下图，写入php后保存会自动转化为x）,没有方法可以绕过。
![image](https://github.com/emlog/emlog/assets/105606015/0b9e53e8-0ff2-477f-8c73-1215d20d41e3)

Here, we are using an alternative method.
这里我们使用另外一种方法。

1.After accessing the backend, use the backup function to back up the database.
   进入后台后使用备份功能备份数据库
![image](https://github.com/emlog/emlog/assets/105606015/693147e8-1b97-4ca4-bdd2-3a6cbbb7fe18)

![image](https://github.com/emlog/emlog/assets/105606015/8147456a-f538-4f8b-935c-8a47e357b0d3)

2.Then, directly edit the database file, and after finding the statement that inserts the extension, add a '.php' extension to it.
   而后直接编辑数据库文件，在找到插入后缀的语句后再在其中增加一个为php的后缀名
![image](https://github.com/emlog/emlog/assets/105606015/55bc730f-a084-4dd3-9c24-77b467e6dffe)

3.Then, import the database again.
   而后重新导入数据库
![image](https://github.com/emlog/emlog/assets/105606015/8e946fc7-caf5-4e05-832d-4888e64139c0)

4.Enter the settings to check, and you will see the '.php' extension.
   进入设置中查看，出现php的后缀
![image](https://github.com/emlog/emlog/assets/105606015/cb370f3b-4f6b-41ff-a086-69b86a0c4734)

5.Then, simply upload a PHP file in the resources section to get shell access.
   而后直接在资源处上传php文件getshell即可
![image](https://github.com/emlog/emlog/assets/105606015/493bb430-68d0-4b2b-acc8-7e1f6c3b7c9d)

![image](https://github.com/emlog/emlog/assets/105606015/4af7a4e1-945e-43e3-84bb-dc242804698c)

![image](https://github.com/emlog/emlog/assets/105606015/c0e1bc2c-0caa-4baa-86dd-20b15251f5e1)

After testing, it has been confirmed that this vulnerability exists from emlog_pro2.1.9 to emlog_pro2.1.14, allowing for shell access. Other versions have not been tested.
   经测试，从emlog_pro2.1.9到emlog_pro2.1.14均存在此漏洞，可以getshell。其它版本未测试。

**Comment by emlog** [comment]
好的，感谢反馈，不过既然都进了后台，那有很多种方法上传 shell，这个还是最麻烦的。
