### ISSUE TITLE
存储型 XSS 漏洞攻击

### ISSUE THREAD

**Issue by yangliukk** [emlog/emlog#253]
目前找到四个问题，第一个之前反馈过
[XSS存储型漏洞一](https://github.com/yangliukk/emlog/blob/main/Storage%20XSS.md)
[XSS存储型漏洞二](https://github.com/yangliukk/emlog/blob/main/Storage%20xss%202.md)
[XSS存储型漏洞三](https://github.com/yangliukk/emlog/blob/main/Storage%20xss%203.md)
[xss存储型漏洞四](https://github.com/yangliukk/emlog/blob/main/Storage%20xss%204.md)

**Comment by emlog** [comment]
收到，感谢反馈，后续版本会修复。
