### ISSUE TITLE
Make Emlog MultiLingual

### ISSUE THREAD

**Issue by codersclub** [emlog/emlog#27]
Hi friends!
Many years I'm watching the Emlog with a great interest.
I offer to convert Emlog from Single-lingual to Multi-lingual.
I think such version will be quite interesting for many users.

For example:
My English demo version: http://codersclub.org/emlog/
There is no problem to add any other language.
I.e. at my localhost I have Chinese + English + Russian language packs installed together.

My current code repository: https://bitbucket.org/vot/emlog
Let's work together!

**Comment by RoyalC** [comment]
hi i know that it's an old one but there already a multilanguage one made by flyers

you can find it at : 

http://emlogfrance.free.fr/index.php

or from chinese site :

https://crazyus.us/emlog6.html

if you want to translate it ro russian it would be great for russian people who need a great cms.

thanks

**Comment by codersclub** [comment]
The CodersClub version of EmLog is multilingual starting from 2014 year :)
Our code is available from public:
https://bitbucket.org/vot/emlog

But where is your code???
