### ISSUE TITLE
Stored Xss Vulnerability

### ISSUE THREAD

**Issue by Ox130e07d** [emlog/emlog#285]
Stored Xss Vulnerability in Article Publishing

1、Write payload in the body of the published article
![image](https://github.com/emlog/emlog/assets/108753162/4ddcc114-fdec-4029-aa43-6e413dd7d743)

2、The vulnerability can be triggered when viewing article content on the home page
![image](https://github.com/emlog/emlog/assets/108753162/4e855833-9821-4e25-ade7-456ee0cc7d35)

3、The vulnerability is located in the following code and is caused by not filtering the fetched content
![image](https://github.com/emlog/emlog/assets/108753162/ea3151be-923d-453c-aaef-799ee53d4a21)

**Comment by Ox130e07d** [comment]
1

**Comment by emlog** [comment]
Thanks for your feedback, but this isn't an issue in our opinion.
