### ISSUE TITLE
SQL slow query

### ISSUE THREAD

**Issue by 52linglong** [emlog/emlog#294]
\# Time: 2024-04-28T19:32:39.833322+08:00
\# User@Host: root[root] @ localhost [127.0.0.1]  Id:     6
\# Query_time: 4.150410  Lock_time: 0.000071 Rows_sent: 7  Rows_examined: 73377
SET timestamp=1714303959;
SELECT gid, title FROM \`emlog_blog\` WHERE (\`type\`='page') AND (\`hide\`='n');
\# Time: 2024-04-28T19:36:46.653501+08:00
\# User@Host: root[root] @ localhost [127.0.0.1]  Id:     7
\# Query_time: 3.797827  Lock_time: 0.000094 Rows_sent: 7  Rows_examined: 73377
SET timestamp=1714304206;
SELECT gid, title FROM \`emlog_blog\` WHERE (\`type\`='page') AND (\`hide\`='n');

问题应该源自：content/plugins/tpl_options/tpl_options.php->getPages()

是否优化将 type 和 hide 添加索引？

**Comment by 52linglong** [comment]
已经有了 KEY top (top,date)，是否添加 KEY sortop (sortop,date)？

**Comment by emlog** [comment]
抱歉，现在才回复，文章表数据大概有多少？偶发还是每次都很慢？原则上不会加太多索引，因为区分度都不大，可能效果也不好。
