### ISSUE TITLE
maybe the admin/views/images/avatar.svg should be at public dir?

### ISSUE THREAD

**Issue by passwa11** [emlog/emlog#297]
https://github.com/emlog/emlog/blob/9288017568f149a858c03b8ecc3b500082d96b4c/content/templates/default/module.php#L582

if the admin dir was Protected by 401 authorizations ,when the site visitor access the site,the comment user's avatar can't be load forbidenen by the Protection.

maybe the default  comment user's avatar should be at public dir ? like default content/template/default/images or others public dir ?

**Comment by emlog** [comment]
Thanks for your feedback, but，I don't think the admin directory is anything special and needs to be protected, so there seems to be no better place to put this static file.

**Comment by passwa11** [comment]
maybe can put it at content/uploadfile ?
The admin folder is protected to prevent people from brute-force hacking the login interface.

**Comment by emlog** [comment]
There is no suitable place for the moment. I think more complex passwords and other security measures should be used to resist attacks.
