### ISSUE TITLE
草稿也会生成文章标签

### ISSUE THREAD

**Issue by SCX-snow** [emlog/emlog#298]
在草稿中设置文章标签也会生成对应的文章标签并出现在主页的标签展示栏中，这是否不太符合操作习惯，私以为是否应该在文章发布之后再生成标签会好一些。

**Comment by emlog** [comment]
收到了，感谢您的反馈，不过我感觉修复这个问题给系统带来的复杂度，比他可能引起的问题还大。其实避免也比较简单，就是下次写草稿的时候先不要写标签。总之保持系统的简单可维护也挺重要的。
