### ISSUE TITLE
使用python调用接口不成功，这是为啥？

### ISSUE THREAD

**Issue by chenlip** [emlog/emlog#300]
获取文章的详情接口
接口URL：https://yourdomain/?rest-api=article_detail
请求方式：GET
接口鉴权方式：无需鉴权
返回格式：JSON
请求参数：
id | 是 | 文章ID

Python调用代码如下：
def site_post_detail(self, postid:str) -> dict:
        '''
            获取文章详细信息
        '''
        data = {"id":int(postid)}
        resp = requests.get(self.baseconf.EMLOG_API_POST_DETAIL, data=data)
        return resp.json()

调用后，返回的结果：（获取不到文章的详细信息，这是为啥？）
{'code': 0, 'msg': 'ok', 'data': {'article': ''}}

**Comment by emlog** [comment]
检查下文章id是不是真实存在。

**Comment by chenlip** [comment]
1、文章的ID是存在的，
2、如果id不存在，返回的数据中'msg'不会ok吧？

哪里有访问文章列表api的示例？

**Comment by jaeheng** [comment]
> 1、文章的ID是存在的， 2、如果id不存在，返回的数据中'msg'不会ok吧？
> 
> 哪里有访问文章列表api的示例？

经测试文章ID不存在也会显示msg=ok，所以还是需要检查下请求的数据是否正确
