### ISSUE TITLE
官网下的5.3.1版本包存在问题

### ISSUE THREAD

**Issue by MikeCoder** [emlog/emlog#36]
![snip20160203_6](https://cloud.githubusercontent.com/assets/3142935/12786557/93fa2866-cacc-11e5-93ac-d6b8b9e91191.png)

安装后直接使用，会出现如上错误。

**解决办法**：

`/src/include/lib/cache.php` 的195行
```php
194 while($row = $this->db->fetch_array($query)) {
195	$$row['option_name'] = $row['option_value'];
196 }
197 $query = $this->db->query("SELECT * FROM " . DB_PREFIX . "comment WHERE hide='n' ORDER BY date DESC LIMIT 0, $index_comnum");
```
中的195行，改为: `${$row['option_name']} = $row['option_value'];`

**系统环境**：
```sh
~  ᐅ php -v
PHP 7.0.2 (cli) (built: Jan  7 2016 10:40:26) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies

~  ᐅ uname -a
Darwin Snail 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
```

**Comment by vibbow** [comment]
https://github.com/emlog/emlog/blob/master/src/include/lib/cache.php#L186
该问题在最新版里已经修复了。

5.3.1 没有测试过和 PHP 7.0.x 的兼容性。你可以直接使用git里的最新版，是和 PHP 7.0.x 测试兼容的。

**Comment by MikeCoder** [comment]
好的，谢谢。：）
