### ISSUE TITLE
论坛你注册这块难道不是个死循环吗？

### ISSUE THREAD

**Issue by MissMin** [emlog/emlog#47]
注册需要邀请码 ->
邀请码需要发布模板 ->
发布模板需要注册 -> 
注册需要邀请码 ！
我凑，难道我没找对地方？

**Comment by wangneal** [comment]
确实是个死循环

**Comment by MissMin** [comment]
有没有官方的同志过来招呼一下啊。。。

**Comment by wangneal** [comment]
不用等了，emlog官方已经放弃这个项目了，市面上的其他高版本的都是别人DIY并自己优化的。大家可以去看看别的版本了
