### ISSUE TITLE
emlog v6.0.0 zip template getshell vulnerability

### ISSUE THREAD

**Issue by Rand0mPythoner** [emlog/emlog#55]
**different as plugin,in the same function but not same includer.**
vul founded in admin\template.php line 95:
upload a zip file with webshell in this page.
![image](https://user-images.githubusercontent.com/18096032/71571926-cfdf9500-2b17-11ea-9986-ef5264c71fab.png)
Limit in include\lib\function.base.php line 759,
![image](https://user-images.githubusercontent.com/18096032/71571941-e4bc2880-2b17-11ea-9f18-8bbd2b630325.png)
we need create a dir named header.php and touch a webshell named header.php too.
like this：
![image](https://user-images.githubusercontent.com/18096032/71572001-2056f280-2b18-11ea-85ce-83775cb4a615.png)
upload and gotshell:
content/templates/header.php/header.php?1=phpinfo();
![image](https://user-images.githubusercontent.com/18096032/71572049-53998180-2b18-11ea-8429-6e8efb7e3cdc.png)

**Comment by johnlui** [comment]
你在自己的博客后台上传 webshell 当然没人管啦。。。

**Comment by Rand0mPythoner** [comment]
> 你在自己的博客后台上传 webshell 当然没人管啦。。。
后台是能远程登陆的，算是后台getshell的点
