### ISSUE TITLE
服务器空间PHP不支持MySql数据库

### ISSUE THREAD

**Issue by lics1216** [emlog/emlog#56]
点击安装最后一步显示，服务器空间PHP不支持MySql数据库

**Comment by Micraow** [comment]
我安装成功，但装插件时有问题

**Comment by kawashiro-ryofu** [comment]
是不是MariaDB不支持啊，我的也出现了这样的情况（PHP7.4 + MariaDB + Apache）

**Comment by kawashiro-ryofu** [comment]
我解决了，安装php之后不会默认安装php-mysql
```bash
$ sudo apt install php7.4-mysql
```

这是我在debian linux下的解决方案，其他平台不知道

**Comment by OwO996** [comment]
换成5.6就好了。。。他不支持高版本。
