### ISSUE TITLE
EMLOG 后台登录问题

### ISSUE THREAD

**Issue by mengxcn** [emlog/emlog#71]
1.EMLOG的登录失败提示功能，一个合格的登录系统不应该暴露帐户是否存在，容易被人暴力破解。账号或密码错误应该一致提示：账号或密码错误。

2.后台登录验证码可爆破，相当于摆设可被hack恶心爆破

修复方法在/admin/globals.php 第33行else后新增 unset($_SESSION['code']);

每判断一次，如果抛出错误就销毁$_SESSION['code']，只要出现密码错误一次后，就自动销毁了$_SESSION['code'],

**Comment by emlog** [comment]
pro 已修复。
