### ISSUE TITLE
emlog v6.0.0-stable has SQL Injection vulnerability

### ISSUE THREAD

**Issue by ghost** [emlog/emlog#74]
Login Required admin.vulnerability in admin/navbar.php line 77:

```
if ($action== 'add_page') {
    $pages = isset($_POST['pages']) ? $_POST['pages'] : array();

    if (empty($pages)) {
        emDirect("./navbar.php?error_e=1");
    }
    
    foreach ($pages as $id => $title) {
        $Navi_Model->addNavi($title, '', 0, 0, 'n', Navi_Model::navitype_page, $id);
    }

    $CACHE->updateCache('navi');
    emDirect('./navbar.php?active_add=1');
}
```

There is no filtering for the `pages` parameter and passed into the addNavi method.

in include/model/navi_model.php line 60:

```
function addNavi($name, $url, $taxis, $pid, $newtab, $type = 0, $typeId = 0) {
        if($taxis > 30000 || $taxis < 0) {
            $taxis = 0;
        }
        $sql="insert into ".DB_PREFIX."navi (naviname,url,taxis,pid,newtab,type,type_id) values('$name','$url', $taxis, $pid, '$newtab', $type, $typeId)";
        $this->db->query($sql);
    }
```

obviously, there is an INSERT SQL Injection vulnerability,we can use single quotation marks to close and inject. use burpsuite and sqlmap to verify this vulnerability:
<img width="1280" alt="iShot2021-03-31 23 34 54" src="https://user-images.githubusercontent.com/37724890/113171556-29ce8d80-927a-11eb-8d20-a48a428ab388.png">

<img width="1208" alt="iShot2021-03-31 23 31 01" src="https://user-images.githubusercontent.com/37724890/113171644-3d79f400-927a-11eb-9afc-b019295633a8.png">

**Comment by emlog** [comment]
get . thank u.

**Comment by emlog** [comment]
fixed in emlog pro .
