### ISSUE TITLE
emlog 6.0 has XSS Vulnerability 

### ISSUE THREAD

**Issue by XD-519** [emlog/emlog#79]
在文章评论处提交评论
![1](https://user-images.githubusercontent.com/81352522/113557735-154f1400-9631-11eb-860b-bad518d2c9c5.JPG)
然后在后台查看评论，点击
![2](https://user-images.githubusercontent.com/81352522/113557838-3e6fa480-9631-11eb-9a9c-921a23ead1cb.JPG)

**Comment by emlog** [comment]
收到 非常感谢。

**Comment by emlog** [comment]
https://github.com/twbs/bootstrap/issues/20184
是一个bootstrap的bug，但是他们不准备修复。。。我得想想其他办法。或则你们有好的修复方式吗？

**Comment by emlog** [comment]
fixed
